version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw
    volumes:
      - ./staticfiles:/app/backend/staticfiles  # If you have static files
      - ./media:/app/backend/media              # If you have media files

  django_app:
    build:
      context: .
    image: izumi09/notes-app
    container_name: "django_cont"
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - ./db.sqlite3:/app/backend/db.sqlite3  # Persist SQLite database
      - ./staticfiles:/app/backend/staticfiles
      - ./media:/app/backend/media
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
